services:
  django:
    image: python:latest
    volumes:
      - ${BACKEND_DIR}:/app
    working_dir: /app
    environment:
      - PYTHONBUFFERED=1
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=backend.settings
    command: >
      bash -c "
        pip install -r /app/requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:${BACKEND_PORT}"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - app_network

  react:
    image: node:latest
    volumes:
      - ${FRONTEND_DIR}:/app
    working_dir: /app
    command: npm start
    ports:
      - ${FRONTEND_PORT}:3000
    networks:
      - app_network

  postgres:
    image: postgres:latest
    environment:
      - PGDATA="/data"
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USR}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
    volumes:
      - ${DATABASE_DIR}/data:/data
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
  app_network: