services:
  django:
    image: python:latest
    volumes:
      - ${BACKEND_DIR}:/app
    working_dir: /app
    environment:
      - PYTHONBUFFERED=1
    command: >
      bash -c "configs:
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - ${BACKEND_PORT}:8000
    networks:
      - app_network

  react:
    image: node:latest
    volumes:
      - ${FRONTEND_DIR}:/app
    working_dir: /app
    command: npm start
    ports:
      - ${FRONTEND_PORT}:3000
    networks:
      - app_network

  postgres:
    image: postgres:latest
    environment:
      - PGDATA="/data"
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USR}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    volumes:
      - ${DATABASE_DIR}/data:/data
    ports:
      - 5432:5432

networks:
  app_network: